[profile.default]

cache = true
cache_path = 'cache'
evm_version = 'cancun'

libs = ['lib']
names = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
src = 'src'
script = 'script'
test = 'test'
